# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ********REQUIRED********
node:
  hostname: 'node1' # Your kube node's hostname
  port: 32565 # Port nodeport
# ************************

minecraft:
  gamemode: 'survival'
  motd: 'Your super-cool, super-kube, minecraft server' # Message of the Day
  port: 25565
  whitelistusers: "godtolo"

volume:
  storage: 10Gi
  path: '/home/kube-local-storage/minecraft' # Path to wherever you want to save your worldfile

resources:
  limits:
    memory: 2.5Gi
  requests:
    memory: 1.5Gi

serviceAccount:
  create: true
